#!/usr/bin/python3 -su

## Copyright (C) 2026 - 2026 ENCRYPTED SUPPORT LLC <adrelanos@whonix.org>
## See the file COPYING for copying conditions.

## AI-Assisted

"""
Shared harness for the tor-control-panel regression tests.

tor-control-panel (which now also contains the merged anon-connection-wizard)
is a PyQt5 GUI that, in normal operation, reads and writes torrc drop-in files
under system paths (/usr/local/etc/torrc.d, /run/anon-connection-wizard) and
shells out to privileged 'leaprun' helpers. None of that is available (or
desirable) in a test/CI sandbox.

This module provides:
  * a single offscreen QApplication (QT_QPA_PLATFORM=offscreen), so widgets can
    be constructed with no X server;
  * source resolution: the tor_control_panel package is imported from a
    tor-control-panel checkout given by TCP_REPO, else from the installed
    /usr/lib/python3/dist-packages;
  * a sandbox() context manager that redirects the torrc/comm-file path
    constants to a private temp dir and replaces the privileged
    write_to_temp_then_move()/subprocess plumbing with an in-process stub that
    just applies the generated content to the fake torrc file -- reproducing the
    observable effect (torrc ends up with the new content) without root,
    privleap, or a real Tor daemon.

No root, no network, no real Tor.
"""

import contextlib
import os
import sys
import tempfile
from pathlib import Path

## The Qt offscreen platform plugin lets the PyQt5 GUI code run without an X
## server or display. Must be set before QApplication is created.
os.environ.setdefault("QT_QPA_PLATFORM", "offscreen")


def _resolve_source() -> None:
    """Put the tor_control_panel package on sys.path.

    TCP_REPO, when set, points at a tor-control-panel checkout; the package
    lives under usr/lib/python3/dist-packages inside it. Otherwise fall back to
    the installed location.
    """
    repo = os.environ.get("TCP_REPO", "").strip()
    if repo:
        candidate = os.path.join(repo, "usr", "lib", "python3", "dist-packages")
        if not os.path.isdir(os.path.join(candidate, "tor_control_panel")):
            raise SystemExit(
                f"TCP_REPO={repo} does not contain "
                f"usr/lib/python3/dist-packages/tor_control_panel"
            )
        sys.path.insert(0, candidate)
    ## When TCP_REPO is unset the installed package on the default sys.path is
    ## used, exactly like the other dist-ai suites.


_resolve_source()

from PyQt5.QtWidgets import QApplication  # noqa: E402

## A single QApplication must exist for the lifetime of the process; creating a
## second one aborts. Reuse any instance a test runner already made.
APP: QApplication = QApplication.instance() or QApplication(["tor-control-panel-tests"])

## Imported after the source is resolved and the QApplication exists.
from tor_control_panel import torrc_gen, tor_status  # noqa: E402


def _bridges_default_path() -> str:
    """Resolve the default-bridges JSON (shipped under usr/share)."""
    repo = os.environ.get("TCP_REPO", "").strip()
    if repo:
        candidate = os.path.join(
            repo, "usr", "share", "anon-connection-wizard", "bridges_default"
        )
        if os.path.isfile(candidate):
            return candidate
    ## Installed location, matching torrc_gen's own default.
    return torrc_gen.bridges_default_path


DEFAULT_TORRC = (
    "# This file is generated by and should ONLY be used by tor-control-panel.\n"
    "DisableNetwork 0\n"
)


@contextlib.contextmanager
def sandbox(initial_torrc: str = DEFAULT_TORRC):
    """Redirect torrc paths to a temp dir and neutralise privileged writes.

    Within the context:
      * torrc_gen.torrc_file_path / torrc_gen.torrc_user_file_path and
        tor_status.torrc_file_path / tor_status.acw_comm_file_path point at
        files inside a private temp directory (torrc seeded with
        ``initial_torrc``);
      * torrc_gen.write_to_temp_then_move and tor_status.write_to_temp_then_move
        are replaced with a stub that writes ``content`` straight to the fake
        torrc file -- the same net effect the real privileged 'acw-write-torrc'
        helper would produce;
      * tor_status.subprocess.call / .check_call are stubbed to succeed, so the
        'leaprun ...' invocations become no-ops.

    Yields the pathlib.Path of the fake torrc file.
    """
    ## Common.torrc_file_path is a class attribute bound at import time to the
    ## real installed path; redirect it too, else AnonConnectionWizard.__init__
    ## regenerates the torrc over the seeded one.
    from tor_control_panel import anon_connection_wizard as _acw
    from tor_control_panel import privilege as _privilege

    saved = {
        "gen_torrc_path": torrc_gen.torrc_file_path,
        "gen_user_path": torrc_gen.torrc_user_file_path,
        "status_torrc_path": tor_status.torrc_file_path,
        "status_comm_path": tor_status.acw_comm_file_path,
        "gen_write": torrc_gen.write_to_temp_then_move,
        "status_write": tor_status.write_to_temp_then_move,
        "resolv_add": torrc_gen.edit_etc_resolv_conf_add,
        "bridges_default": torrc_gen.bridges_default_path,
        "priv_run": _privilege.run,
        "priv_check_run": _privilege.check_run,
        "priv_command": _privilege.command,
        "acw_common_torrc": _acw.Common.torrc_file_path,
    }

    with tempfile.TemporaryDirectory(prefix="tcp-test-") as tmp:
        torrc_path = Path(tmp) / "40_tor_control_panel.conf"
        user_path = Path(tmp) / "50_user.conf"
        comm_path = Path(tmp) / "tor.conf"
        torrc_path.write_text(initial_torrc, encoding="utf-8")
        user_path.write_text("", encoding="utf-8")

        def _stub_write(content: str) -> None:
            ## The real helper moves the staged content into the torrc file.
            torrc_path.write_text(content, encoding="utf-8")

        def _stub_ok(*_args, **_kwargs) -> int:
            return 0

        torrc_gen.torrc_file_path = str(torrc_path)
        torrc_gen.torrc_user_file_path = str(user_path)
        torrc_gen.bridges_default_path = _bridges_default_path()
        tor_status.torrc_file_path = str(torrc_path)
        tor_status.acw_comm_file_path = str(comm_path)
        ## torrc_gen imported these by name; patch them in its namespace.
        torrc_gen.write_to_temp_then_move = _stub_write
        torrc_gen.edit_etc_resolv_conf_add = lambda *a, **k: None
        tor_status.write_to_temp_then_move = _stub_write
        ## The privileged leaprun/pkexec runner is stubbed so set_enabled /
        ## set_disabled do not shell out during tests. command() (used by the
        ## Popen call sites: restart/stop/log-read) returns a harmless argv so a
        ## real Popen(['true']) succeeds everywhere, including CI where neither
        ## leaprun nor pkexec exists.
        _privilege.run = _stub_ok
        _privilege.check_run = lambda *a, **k: None
        _privilege.command = lambda action, *a: ["true"]
        _acw.Common.torrc_file_path = str(torrc_path)

        try:
            yield torrc_path
        finally:
            _acw.Common.torrc_file_path = saved["acw_common_torrc"]
            torrc_gen.torrc_file_path = saved["gen_torrc_path"]
            torrc_gen.torrc_user_file_path = saved["gen_user_path"]
            torrc_gen.bridges_default_path = saved["bridges_default"]
            tor_status.torrc_file_path = saved["status_torrc_path"]
            tor_status.acw_comm_file_path = saved["status_comm_path"]
            torrc_gen.write_to_temp_then_move = saved["gen_write"]
            torrc_gen.edit_etc_resolv_conf_add = saved["resolv_add"]
            tor_status.write_to_temp_then_move = saved["status_write"]
            _privilege.run = saved["priv_run"]
            _privilege.check_run = saved["priv_check_run"]
            _privilege.command = saved["priv_command"]


@contextlib.contextmanager
def no_modal():
    """Neutralise the blocking modal loops so widgets can be built headless.

    Both AnonConnectionWizard.__init__ (via setup_ui) and TorControlPanel.__init__
    call self.exec_()/self.show()+exec, entering a modal event loop that never
    returns without user interaction. Under this context those become no-ops, so
    a test can construct the widget, inspect it, and invoke handlers directly.
    Also stubs QMessageBox.exec_ so any dialog raised by a handler cannot block.
    """
    from PyQt5.QtWidgets import QDialog, QMessageBox
    from tor_control_panel import anon_connection_wizard as acw
    from tor_control_panel import tor_bootstrap
    from tor_control_panel import tor_control_panel as tcp

    saved = {
        "acw_exec": acw.AnonConnectionWizard.exec_,
        "mbox_exec": QMessageBox.exec_,
        "mbox_exec_slot": QMessageBox.exec,
        "dialog_exec": QDialog.exec_,
        "bootstrap_start": tor_bootstrap.TorBootstrap.start,
    }
    acw.AnonConnectionWizard.exec_ = lambda self, *a, **k: 0
    QMessageBox.exec_ = lambda self, *a, **k: 0
    QMessageBox.exec = lambda self, *a, **k: 0
    QDialog.exec_ = lambda self, *a, **k: 0
    ## A handler under test (e.g. Accept -> set_torrc -> restart_tor) may start a
    ## real TorBootstrap QThread, whose run() imports stem and talks to a control
    ## socket. Make .start() a no-op so widget tests neither depend on stem nor
    ## spawn a live thread; the live bootstrap is exercised by test_live_tor.
    tor_bootstrap.TorBootstrap.start = lambda self, *a, **k: None
    try:
        yield
    finally:
        acw.AnonConnectionWizard.exec_ = saved["acw_exec"]
        QMessageBox.exec_ = saved["mbox_exec"]
        QMessageBox.exec = saved["mbox_exec_slot"]
        QDialog.exec_ = saved["dialog_exec"]
        tor_bootstrap.TorBootstrap.start = saved["bootstrap_start"]
