#!/bin/bash

## Copyright (C) 2026 - 2026 ENCRYPTED SUPPORT LLC <adrelanos@whonix.org>
## See the file COPYING for copying conditions.

## AI-Assisted

## Regression: dist-installer-cli must refuse to run concurrently with another
## instance of itself (per user). Concurrent runs otherwise collide on the shared
## download directory and on the system-wide apt / modprobe / repository setup.
## The guard is lockfile.sh sourced under a fixed LOCK_NAME ('dist-installer-cli');
## a second run fails fast ('flock: failed to get lock', non-zero).
##
## SUBJECT: the autogenerated self-contained dist-installer-cli-standalone -- the
## artifact end users actually run, and where the lockfile.sh inlining is most
## fragile (an inlined copy must NOT mis-fire lockfile.sh wrap mode on the
## installer's own argument). '-h' exits via usage() in the option loop AFTER the
## top-of-file lock is taken but BEFORE any directory / root / network work, so
## the whole test is hermetic: no root, no network.
##
## Two assertions, each a canary on pre-feature code:
##   1. CONTENTION -- while a holder owns the 'dist-installer-cli' lock, 'standalone
##      -h' exits non-zero with 'flock: failed to get lock'. FAILS on a standalone
##      with no guard (it would print usage and exit 0 regardless).
##   2. INLINE-SAFETY -- with NO contention, 'standalone -h' prints usage and exits
##      0. FAILS if inlining mis-fired lockfile.sh wrap mode (it would abort with a
##      'usage: <lock-key> -- <command>' error on ANY argument).
##
## Exit: 0 pass | 1 fail. A missing subject or lockfile.sh is FATAL, never a skip.

set -o errexit
set -o nounset
set -o pipefail
set -o errtrace
shopt -s inherit_errexit
shopt -s shift_verbose
export LC_ALL=C

[ -v TMP ] || TMP=/tmp

repo="${USABILITY_MISC_REPO:-}"
if [ -z "${repo}" ]; then
   repo="${HOME}/derivative-maker/packages/kicksecure/usability-misc"
fi
standalone="${repo}/usr/share/usability-misc/dist-installer-cli-standalone"

if [ ! -r "${standalone}" ]; then
   printf '%s\n' "FATAL: not readable: '${standalone}'" >&2
   printf '%s\n' "set USABILITY_MISC_REPO to a usability-misc checkout." >&2
   exit 1
fi

## lockfile.sh (the real helper, via wrap mode) is the contention generator: it
## computes the SAME lock file the standalone does for key 'dist-installer-cli',
## so no lock-path mangling is duplicated here. Its absence is an environment bug.
helper_scripts_path="${HELPER_SCRIPTS_PATH:-}"
if [ -z "${helper_scripts_path}" ] \
   && [ -d "${repo}/../helper-scripts/usr/libexec/helper-scripts" ]; then
   helper_scripts_path="${repo}/../helper-scripts"
fi
## Empty base -> absolute '/usr/libexec/...' (the installed helper), matching the
## dist-ai convention; a checkout base yields '<repo>/usr/libexec/...'.
lockfile_sh="${helper_scripts_path}/usr/libexec/helper-scripts/lockfile.sh"
if [ ! -x "${lockfile_sh}" ]; then
   printf '%s\n' "FATAL: lockfile.sh not executable: '${lockfile_sh}'" >&2
   printf '%s\n' "wire HELPER_SCRIPTS_PATH (dist-ai-tests.helper-scripts: true) at a checkout." >&2
   exit 1
fi

## The holder runs this helper UNDER the lock (see below); resolve it next to us.
script_dir="$( cd -- "$( dirname -- "$( readlink --canonicalize -- "${BASH_SOURCE[0]}" )" )" && pwd )"
holder_helper="${script_dir}/concurrency_guard_holder.sh"
if [ ! -x "${holder_helper}" ]; then
   printf '%s\n' "FATAL: holder helper not executable: '${holder_helper}'" >&2
   exit 1
fi

lock_key="dist-installer-cli"
hold_max=30

work="$( mktemp --directory -- "${TMP}/dist-installer-cli-concurrency.XXXXXX" )"
## Private runtime dir so the lock lives here, never the caller's real
## /run/user/EUID, and HOME so a stray download dir cannot escape the work dir.
runtime_dir="${work}/xdg"
mkdir --parents -- "${runtime_dir}"
chmod 0700 -- "${runtime_dir}"

holder_pid=""
# shellcheck disable=SC2317  # reached only via the EXIT trap
cleanup() {
   if [ -n "${holder_pid}" ]; then
      ## holder is a session leader (setsid); kill its whole group so the flock
      ## and its 'sleep' child both die and the lock is released.
      kill -- -"${holder_pid}" 2>/dev/null || true
   fi
   safe-rm --recursive --force -- "${work}"
}
trap cleanup EXIT

run_standalone_h() {
   ## -h after the lock: usage then exit. Bounded so a bug can never hang the suite.
   XDG_RUNTIME_DIR="${runtime_dir}" HOME="${work}" \
      timeout --kill-after=5 30 "${standalone}" -h
}

pass_count=0
fail_count=0
ok() {
   printf '%s\n' "PASS: ${1}"
   pass_count=$(( pass_count + 1 ))
}
notok() {
   printf '%s\n' "FAIL: ${1}" >&2
   if [ -n "${2:-}" ]; then
      printf '%s\n' "      ${2}" >&2
   fi
   fail_count=$(( fail_count + 1 ))
}

## Assertion 1 (INLINE-SAFETY) runs FIRST, before any holder exists, so the lock
## is guaranteed free -- no dependency on releasing a holder, whose process-group
## teardown races the slow PID reaping in a CI container. With the lock free,
## standalone -h self-locks and prints usage (rc 0), proving the inlined lockfile.sh
## body did not mis-fire wrap mode.
free_rc=0
free_out="$( run_standalone_h 2>/dev/null )" || free_rc=$?
if [ "${free_rc}" -eq 0 ] \
   && [[ "${free_out}" == *'Usage:'* ]]; then
   ok "uncontended run self-locks and prints usage (rc=0, no wrap mis-fire)"
else
   notok "uncontended run did not behave as a normal '-h'" \
      "rc=${free_rc} out='$( printf '%s' "${free_out}" | head --lines=1 )'"
fi

## Now start a holder that owns the 'dist-installer-cli' lock under the private
## runtime dir. It runs a command UNDER the lock that first touches a ready marker,
## then sleeps -- so the test can wait for the marker WITHOUT itself trying to
## acquire the lock (an acquiring probe would race the holder). setsid: its own
## process group for a clean group-kill in cleanup.
ready_marker="${work}/holder-ready"
setsid env XDG_RUNTIME_DIR="${runtime_dir}" \
   "${lockfile_sh}" "${lock_key}" -- \
   "${holder_helper}" "${ready_marker}" "${hold_max}" \
   >"${work}/holder.log" 2>&1 &
holder_pid=$!

## Wait (bounded) until the holder signals it holds the lock. Deterministic: the
## marker only appears from inside the locked command, never from a race.
held=0
for _ in $(seq 1 100); do
   if [ -e "${ready_marker}" ]; then
      held=1
      break
   fi
   sleep 0.1
done
if [ "${held}" != 1 ]; then
   printf '%s\n' "FATAL: holder never acquired the '${lock_key}' lock." >&2
   cat -- "${work}/holder.log" >&2 || true
   exit 1
fi

## Assertion 2: CONTENTION -- standalone -h must fail fast with the flock message.
contend_rc=0
contend_err="$( run_standalone_h 2>&1 1>/dev/null )" || contend_rc=$?
if [ "${contend_rc}" -ne 0 ] \
   && [[ "${contend_err}" == *'failed to get lock'* ]]; then
   ok "contended run fails fast (rc=${contend_rc}, 'flock: failed to get lock')"
else
   notok "contended run did not fail fast" \
      "rc=${contend_rc} err='$( printf '%s' "${contend_err}" | tr '\n' ' ' )'"
fi

printf '%s\n' ""
printf '%s\n' "===== dist-installer-cli concurrency guard: ${pass_count} pass, ${fail_count} fail ====="
[ "${fail_count}" -eq 0 ]
