#!/bin/bash

## Copyright (C) 2026 - 2026 ENCRYPTED SUPPORT LLC <adrelanos@whonix.org>
## See the file COPYING for copying conditions.

## AI-Assisted

## Regression: dist-installer-cli must refuse to run concurrently with another
## instance (per user), so concurrent runs do not collide on the shared download
## directory or the system-wide apt / modprobe / repository setup. The guard is an
## in-script per-user flock (acquire_concurrency_lock / release_concurrency_lock),
## acquired after logging is set up and released before the guest boots.
##
## SUBJECT: the autogenerated self-contained dist-installer-cli-standalone. It is
## SOURCED (its run is guarded by was_executed, so sourcing defines the functions
## without running the installer), then acquire_concurrency_lock is driven directly
## -- no root, no network. A private XDG_RUNTIME_DIR isolates the lock.
##
## Assertions (each a canary on code WITHOUT the guard, where the function is
## absent and the first assertion fails):
##   1. a free lock is ACQUIRED;
##   2. a second acquirer (separate open file description) is REFUSED, fast;
##   3. after release the lock is re-acquirable.
##
## Exit: 0 pass | 1 fail. A missing subject is FATAL, never a skip.

set -o errexit
set -o nounset
set -o pipefail
set -o errtrace
shopt -s inherit_errexit
shopt -s shift_verbose
export LC_ALL=C

repo="${USABILITY_MISC_REPO:-}"
if [ -z "${repo}" ]; then
   repo="${HOME}/derivative-maker/packages/kicksecure/usability-misc"
fi
standalone="${repo}/usr/share/usability-misc/dist-installer-cli-standalone"
if [ ! -r "${standalone}" ]; then
   printf '%s\n' "FATAL: not readable: '${standalone}'" >&2
   printf '%s\n' "set USABILITY_MISC_REPO to a usability-misc checkout." >&2
   exit 1
fi

work="$( mktemp --directory )"
# shellcheck disable=SC2317  # reached only via the EXIT trap
cleanup() {
   safe-rm --recursive --force -- "${work}"
}
trap cleanup EXIT

## Private, owned runtime dir so the lock lives here, not the caller's real one.
export XDG_RUNTIME_DIR="${work}/xdg"
mkdir --mode=0700 -- "${XDG_RUNTIME_DIR}"

## Source the self-contained standalone (was_executed guard => defines functions,
## does not run the installer). Set only the globals acquire_concurrency_lock reads;
## shellcheck cannot see that the sourced subject consumes them (SC2034).
# shellcheck disable=SC1090
source "${standalone}" >/dev/null 2>&1
# shellcheck disable=SC2034  # consumed by the sourced standalone, not this file
dry_run_skip_commands=""
# shellcheck disable=SC2034
me="dist-installer-cli"
# shellcheck disable=SC2034
underline=""
# shellcheck disable=SC2034
nounderline=""
dic_lock_fd=""

pass_count=0
fail_count=0
ok() {
   printf '%s\n' "PASS: ${1}"
   pass_count=$(( pass_count + 1 ))
}
notok() {
   printf '%s\n' "FAIL: ${1}" >&2
   if [ -n "${2:-}" ]; then
      printf '%s\n' "      ${2}" >&2
   fi
   fail_count=$(( fail_count + 1 ))
}

## Assertion 1: a free lock is acquired. (On code without the guard the function
## does not exist and this errors out -> the whole test fails: the canary.)
if acquire_concurrency_lock; then
   ok "free lock is acquired (fd=${dic_lock_fd})"
else
   notok "acquire_concurrency_lock failed on a free lock"
fi

## Assertion 2: a second acquirer (a subshell opens its own fd = a distinct open
## file description) is refused fast with the in-progress message.
contend_out="$( ( dic_lock_fd=""; acquire_concurrency_lock ) 2>&1 )" \
   && contend_rc=0 || contend_rc=$?
if [ "${contend_rc}" -ne 0 ] \
   && [[ "${contend_out}" == *'already in progress'* ]]; then
   ok "second acquirer refused while the lock is held"
else
   notok "second acquirer was not refused" \
      "rc=${contend_rc} out='$( printf '%s' "${contend_out}" | tr '\n' ' ' )'"
fi

## Assertion 3: after release the lock is re-acquirable.
release_concurrency_lock
if ( dic_lock_fd=""; acquire_concurrency_lock ); then
   ok "lock re-acquirable after release"
else
   notok "lock not re-acquirable after release"
fi

printf '%s\n' ""
printf '%s\n' "===== dist-installer-cli concurrency guard: ${pass_count} pass, ${fail_count} fail ====="
[ "${fail_count}" -eq 0 ]
