#!/bin/bash

## Copyright (C) 2026 - 2026 ENCRYPTED SUPPORT LLC <adrelanos@whonix.org>
## See the file COPYING for copying conditions.

## AI-Assisted

## Regression (end-to-end): when installing under a TARGET user account
## ('--user=<acct>') with NO explicit '--directory-prefix', the download dir must
## default to the TARGET user's home -- NOT the invoker's home. The download and
## import run AS the target user (run_as_target_user -> sudo -u <target>), so a
## prefix under the invoker's home is not writable by the target and the real
## installer aborted with "mkdir: cannot create directory '/home/<invoker>'".
##
## Before the fix the target home was applied to directory_prefix ONLY under a
## sysmaint invoker; a normal (non-sysmaint) invoker kept the invoker-home
## default. This reproduces that failing environment: a non-sysmaint invoker
## installing under a DIFFERENT account.
##
## SUBJECT: the autogenerated dist-installer-cli-standalone, EXECUTED (not
## sourced), driven through the real get_su_cmd -> not_as_root -> set_variables
## -> parse_opt path. '--getopt' makes parse_opt print the parsed options and
## exit 0 immediately AFTER the directory-resolution + directory-creation block,
## so the real 'sudo -u <target> -- mkdir ...' runs but NO network / apt /
## VirtualBox is touched.
##
## Hermetic (no root, no network, no real accounts): a PATH 'sudo' stub runs each
## command directly as the test user (no real elevation); a PATH 'getent' stub
## resolves the chosen target name to a test-writable tmpdir home (isolates the
## test from the host account database); a PATH 'id' stub answers the target's
## existence check. Every other 'id'/'getent' call delegates to the real tool, so
## the invoker stays the real (non-root, non-sysmaint) test user.
##
## Canary: on the OLD code, scenario 1 resolves directory_prefix to the INVOKER
## home, so the 'directory_prefix=<target-home>/...' assertion (and the
## target-home dir-created assertion) fail.
##
## Exit: 0 pass | 1 fail. A missing subject / helper-scripts, or running as root,
## is FATAL (exit 1), never a silent skip.

set -o errexit
set -o nounset
set -o pipefail
set -o errtrace
shopt -s inherit_errexit
shopt -s shift_verbose
export LC_ALL=C

repo="${USABILITY_MISC_REPO:-}"
if [ -z "${repo}" ]; then
   repo="${HOME}/derivative-maker/packages/kicksecure/usability-misc"
fi
standalone="${repo}/usr/share/usability-misc/dist-installer-cli-standalone"
if [ ! -r "${standalone}" ]; then
   printf '%s\n' "FATAL: not readable: '${standalone}'" >&2
   printf '%s\n' "set USABILITY_MISC_REPO to a usability-misc checkout." >&2
   exit 1
fi

if [ -z "${HELPER_SCRIPTS_PATH:-}" ] \
   && [ -d "${repo}/../helper-scripts/usr/libexec/helper-scripts" ]; then
   export HELPER_SCRIPTS_PATH="${repo}/../helper-scripts"
fi

## The installer logs via helper-scripts' 'sanitize-string', a python3 program
## that imports the 'sanitize_string' package. A CHECKOUT (HELPER_SCRIPTS_PATH)
## does not put it on the default path, so wire its dist-packages dir onto
## PYTHONPATH (the '-Bsu' shebang honors it) -- the real dependency, not stubbed.
if [ -n "${HELPER_SCRIPTS_PATH:-}" ] \
   && [ -d "${HELPER_SCRIPTS_PATH}/usr/lib/python3/dist-packages/sanitize_string" ]; then
   export PYTHONPATH="${HELPER_SCRIPTS_PATH}/usr/lib/python3/dist-packages${PYTHONPATH:+:${PYTHONPATH}}"
fi

## The installer refuses to run as root (not_as_root). This e2e exercises the
## real run_installer flow, so it needs a non-root uid; running the suite as root
## is an environment bug, not something to paper over here.
if [ "$(id -u)" = "0" ]; then
   printf '%s\n' "FATAL: this end-to-end test must run as a non-root user (the installer refuses root)." >&2
   exit 1
fi

target_user="dict-target"

work="$( mktemp --directory )"
# shellcheck disable=SC2317  # reached only via the EXIT trap
cleanup() {
   safe-rm --recursive --force -- "${work}"
}
trap cleanup EXIT

mkdir --parents -- \
   "${work}/bin" "${work}/invokerhome" "${work}/targethome" "${work}/custom"

## PATH 'sudo' stub: drop sudo's own options up to '--' and exec the command
## directly. run_as_target_user -> root_cmd always invokes
## 'sudo --user <target> -- cmd ...', so the privileged mkdir runs as the test
## user (writing into the test-owned tmpdir homes), no real elevation.
cat > "${work}/bin/sudo" <<'STUB'
#!/bin/bash
while [ "$#" -gt 0 ]; do
   if [ "$1" = "--" ]; then
      shift
      break
   fi
   shift
done
exec "$@"
STUB

## PATH 'getent' stub: resolve ONLY the chosen target account to a test-writable
## tmpdir home; delegate everything else (incl. 'getent passwd sysmaint') to the
## real tool. Isolates the test from whatever accounts the host happens to have.
cat > "${work}/bin/getent" <<STUB
#!/bin/bash
if [ "\$1" = passwd ] && [ "\$2" = "${target_user}" ]; then
   printf '%s\n' "${target_user}:x:4242:4242::${work}/targethome:/bin/bash"
   exit 0
fi
exec /usr/bin/getent "\$@"
STUB

## PATH 'id' stub: answer the installer's 'id --user -- <target>' existence check
## for the chosen target; delegate every other call (so 'id --name --user' and
## 'id -u' resolve to the real, non-root, non-sysmaint test user).
cat > "${work}/bin/id" <<STUB
#!/bin/bash
for arg in "\$@"; do
   if [ "\$arg" = "${target_user}" ]; then
      exit 0
   fi
done
exec /usr/bin/id "\$@"
STUB

chmod +x -- "${work}/bin/sudo" "${work}/bin/getent" "${work}/bin/id"

pass_count=0
fail_count=0
ok() {
   printf '%s\n' "PASS: ${1}"
   pass_count=$(( pass_count + 1 ))
}
notok() {
   printf '%s\n' "FAIL: ${1}" >&2
   if [ -n "${2:-}" ]; then
      printf '%s\n' "      ${2}" >&2
   fi
   fail_count=$(( fail_count + 1 ))
}

## Run the real standalone to the '--getopt' early-exit and echo the resolved
## 'directory_prefix=' line. HOME is a test-owned tmpdir so the invoker-home
## default is deterministic and distinct from the target home. stderr (the
## installer's logging) is kept for diagnostics on failure.
resolved_prefix() {
   local out err rc=0
   out="${work}/out"
   err="${work}/err"
   PATH="${work}/bin:${PATH}" HOME="${work}/invokerhome" \
      timeout --kill-after=10 60 \
      bash "${standalone}" "$@" --getopt >"${out}" 2>"${err}" || rc="$?"
   ## '--getopt' exits 0; a non-zero rc means the real directory step aborted
   ## (e.g. the pre-fix failure). Surface the resolved value regardless so the
   ## assertion message is meaningful.
   grep --max-count=1 -- '^directory_prefix=' "${out}" | cut -d= -f2- || printf '%s' "<none:rc=${rc}>"
}

## Scenario 1 (CANARY): target user, no '--directory-prefix' -> the TARGET home.
got="$( resolved_prefix --user="${target_user}" )"
want="${work}/targethome/dist-installer-cli-download"
if [ "${got}" = "${want}" ]; then
   ok "target user (no -P) resolves the download dir to the TARGET home"
else
   notok "target user (no -P) did NOT resolve to the target home" \
      "want='${want}' got='${got}' ($(tail -n1 -- "${work}/err"))"
fi
## The real 'sudo -u <target> -- mkdir' must have created that dir (pre-fix it is
## created under the invoker home instead, so this dir is absent).
if [ -d "${want}" ]; then
   ok "target-home download dir was actually created by the real directory step"
else
   notok "target-home download dir was not created" "missing: '${want}'"
fi

## Scenario 2: no target user, no '-P' -> the INVOKER home (same-account default).
got="$( resolved_prefix )"
want="${work}/invokerhome/dist-installer-cli-download"
if [ "${got}" = "${want}" ]; then
   ok "no target user resolves the download dir to the invoker home"
else
   notok "no target user did NOT resolve to the invoker home" \
      "want='${want}' got='${got}'"
fi

## Scenario 3: explicit '--directory-prefix' wins over the target-home default.
want="${work}/custom/pfx"
got="$( resolved_prefix --user="${target_user}" --directory-prefix="${want}" )"
if [ "${got}" = "${want}" ]; then
   ok "explicit --directory-prefix is preserved for a target user"
else
   notok "explicit --directory-prefix was overridden" \
      "want='${want}' got='${got}'"
fi

printf '%s\n' ""
printf '%s\n' "===== dist-installer-cli --user directory_prefix default: ${pass_count} pass, ${fail_count} fail ====="
[ "${fail_count}" -eq 0 ]
