#!/bin/bash

## Copyright (C) 2026 - 2026 ENCRYPTED SUPPORT LLC <adrelanos@whonix.org>
## See the file COPYING for copying conditions.

## AI-Assisted

## Regression (end-to-end): a '--dry-run' invocation must SIMULATE the whole
## install/import flow and exit 0, never crash. This is the faithful reproduction
## of the reported bug where a dry-run aborted with exit 141 (SIGPIPE) at the
## per-run log-dir step and, more generally, of the dry-run gaps throughout the
## pipeline (forced realpath, free-space df, VM-existence detection, host
## virtualizer install, kernel-module readiness) where a skipped command's
## result was consumed as if it had run.
##
## SUBJECT: the autogenerated dist-installer-cli-standalone, EXECUTED (not
## sourced) under '--dry-run' with the reported Whonix scenario. Hermetic: a PATH
## 'sudo' stub runs each command directly (no real elevation); every
## side-effecting command is dry-run-skipped by the installer itself; the
## read-only probes it forces (realpath, df, 'vboxmanage showvminfo') run as the
## test user -- 'vboxmanage' is absent, so no VM is detected and the import is
## simulated. No root, no network, no VirtualBox.
##
## Canary: on code WITHOUT the fixes the dry-run aborts (exit 141 / 'Signal
## received: PIPE', or a realpath 'No such file' abort), so the exit-0 +
## 'SUCCESS' assertions fail.
##
## Exit: 0 pass | 1 fail. A missing subject is FATAL, never a skip.

set -o errexit
set -o nounset
set -o pipefail
set -o errtrace
shopt -s inherit_errexit
shopt -s shift_verbose
export LC_ALL=C

repo="${USABILITY_MISC_REPO:-}"
if [ -z "${repo}" ]; then
   repo="${HOME}/derivative-maker/packages/kicksecure/usability-misc"
fi
standalone="${repo}/usr/share/usability-misc/dist-installer-cli-standalone"
if [ ! -r "${standalone}" ]; then
   printf '%s\n' "FATAL: not readable: '${standalone}'" >&2
   printf '%s\n' "set USABILITY_MISC_REPO to a usability-misc checkout." >&2
   exit 1
fi

if [ -z "${HELPER_SCRIPTS_PATH:-}" ] \
   && [ -d "${repo}/../helper-scripts/usr/libexec/helper-scripts" ]; then
   export HELPER_SCRIPTS_PATH="${repo}/../helper-scripts"
fi

## The installer refuses to run as root (not_as_root). This e2e exercises the
## real run_installer flow, so it needs a non-root uid; running the suite as
## root is an environment bug, not something to paper over here.
if [ "$(id -u)" = "0" ]; then
   printf '%s\n' "FATAL: this end-to-end test must run as a non-root user (the installer refuses root)." >&2
   exit 1
fi

work="$( mktemp --directory )"
# shellcheck disable=SC2317  # reached only via the EXIT trap
cleanup() {
   safe-rm --recursive --force -- "${work}"
}
trap cleanup EXIT

## PATH 'sudo' stub: drop sudo's own options up to '--' and exec the command
## directly. root_cmd always invokes 'sudo [--user U] [--chdir D] -- cmd ...', so
## the real privileged commands run as the test user; a genuinely-absent command
## (vboxmanage) still fails as it would in production.
mkdir --parents -- "${work}/bin"
cat > "${work}/bin/sudo" <<'STUB'
#!/bin/bash
while [ "$#" -gt 0 ]; do
   if [ "$1" = "--" ]; then
      shift
      break
   fi
   shift
done
exec "$@"
STUB
chmod +x -- "${work}/bin/sudo"

directory_prefix="${work}/download"
mkdir --parents -- "${directory_prefix}"

pass_count=0
fail_count=0
ok() {
   printf '%s\n' "PASS: ${1}"
   pass_count=$(( pass_count + 1 ))
}
notok() {
   printf '%s\n' "FAIL: ${1}" >&2
   if [ -n "${2:-}" ]; then
      printf '%s\n' "      ${2}" >&2
   fi
   fail_count=$(( fail_count + 1 ))
}

out_file="${work}/out.log"
rc=0
PATH="${work}/bin:${PATH}" timeout --kill-after=10 300 bash "${standalone}" \
   --guest=whonix --guest-version=18.2.1.9 --interface=lxqt \
   --user="$(id --user --name)" --directory-prefix="${directory_prefix}" \
   --non-interactive --no-boot --import-only=both --destroy-existing-guest \
   --dry-run >"${out_file}" 2>&1 || rc="$?"

## 1. The run must exit 0.
if [ "${rc}" -eq 0 ]; then
   ok "dry-run exits 0"
else
   notok "dry-run exited non-zero (rc=${rc})" "$(tail -n3 -- "${out_file}" | tr '\n' '|')"
fi

## 2. It must report success (proves it reached the end, not just an early return).
if grep --quiet --fixed-strings "Installer Result: 'SUCCESS'" -- "${out_file}"; then
   ok "dry-run reports Installer Result: SUCCESS"
else
   notok "dry-run did not report SUCCESS"
fi

## 3. The specific reported crash must be absent.
if grep --quiet --fixed-strings "Signal received: 'PIPE'" -- "${out_file}"; then
   notok "handle_exit took a SIGPIPE (the reported 141 crash)"
else
   ok "no SIGPIPE in the error handler"
fi

## 4. The forced realpath must not have aborted on the not-yet-created log dir.
if grep --quiet --extended-regexp "realpath: .*No such file or directory" -- "${out_file}"; then
   notok "forced realpath failed on a missing path (copy_thru_barrier gap)"
else
   ok "forced realpath tolerated the simulated (missing) log dir"
fi

printf '%s\n' ""
printf '%s\n' "===== dist-installer-cli --dry-run end-to-end: ${pass_count} pass, ${fail_count} fail ====="
[ "${fail_count}" -eq 0 ]
