#!/bin/bash

## Copyright (C) 2026 - 2026 ENCRYPTED SUPPORT LLC <adrelanos@whonix.org>
## See the file COPYING for copying conditions.

## AI-Assisted

## Regression: the error-exit handler must report the REAL exit code, never turn
## an error into a bogus SIGPIPE (141). On an error the ERR/EXIT trap runs
## handle_exit, which prints a few lines of source context around the failing
## line. The old code did this with 'pr -tn "${0}" | tail | head' pipelines:
## 'head' closes the pipe after a few lines while 'pr' keeps streaming the
## multi-thousand-line script, so the writers take SIGPIPE; under 'set -o
## pipefail' the pipeline returns 141, under errexit+inherit_errexit that is
## fatal, and -- because the trap was still armed inside the handler -- it
## RE-ENTERS, masking the original error as '141 PIPE'. The fix disarms the trap
## at handler entry and reads the context with a single 'awk' pass (no pipe ->
## no SIGPIPE), so the handler exits with the genuine code.
##
## SUBJECT: the autogenerated dist-installer-cli-standalone. A generated driver
## SOURCES it (was_executed guard => functions only, installer does not run),
## arms the real trap via set_trap, then runs 'false' to raise a genuine error.
## The driver is padded far past the pipe buffer so that, on the old code, 'pr'
## is guaranteed to overrun a closed pipe -- making the SIGPIPE deterministic.
## No root, no network.
##
## Canary: on code WITHOUT the fix the driver exits 141 (or is killed as a
## runaway re-entrant loop), not 1 -> assertion fails.
##
## Exit: 0 pass | 1 fail. A missing subject is FATAL, never a skip.

set -o errexit
set -o nounset
set -o pipefail
set -o errtrace
shopt -s inherit_errexit
shopt -s shift_verbose
export LC_ALL=C

repo="${USABILITY_MISC_REPO:-}"
if [ -z "${repo}" ]; then
   repo="${HOME}/derivative-maker/packages/kicksecure/usability-misc"
fi
standalone="${repo}/usr/share/usability-misc/dist-installer-cli-standalone"
if [ ! -r "${standalone}" ]; then
   printf '%s\n' "FATAL: not readable: '${standalone}'" >&2
   printf '%s\n' "set USABILITY_MISC_REPO to a usability-misc checkout." >&2
   exit 1
fi

if [ -z "${HELPER_SCRIPTS_PATH:-}" ] \
   && [ -d "${repo}/../helper-scripts/usr/libexec/helper-scripts" ]; then
   export HELPER_SCRIPTS_PATH="${repo}/../helper-scripts"
fi

work="$( mktemp --directory )"
# shellcheck disable=SC2317  # reached only via the EXIT trap
cleanup() {
   safe-rm --recursive --force -- "${work}"
}
trap cleanup EXIT

pass_count=0
fail_count=0
ok() {
   printf '%s\n' "PASS: ${1}"
   pass_count=$(( pass_count + 1 ))
}
notok() {
   printf '%s\n' "FAIL: ${1}" >&2
   if [ -n "${2:-}" ]; then
      printf '%s\n' "      ${2}" >&2
   fi
   fail_count=$(( fail_count + 1 ))
}

## Build the driver: the error ('false') is near the TOP so 'tail -n+(line-4)'
## would forward almost the whole file, and thousands of trailing comment lines
## pad it far past the ~64 KiB pipe buffer. '${0}' inside the sourced handle_exit
## is this driver, so 'pr' reads these padded lines.
driver="${work}/driver.sh"
{
   printf '%s\n' '#!/bin/bash'
   printf '%s\n' '## shellcheck disable=SC1090'
   ## '${STANDALONE}' is a literal: it is expanded at the generated driver's
   ## runtime (from the env below), not here.
   # shellcheck disable=SC2016
   printf '%s\n' 'source "${STANDALONE}" >/dev/null 2>&1'
   ## globals handle_exit's log path reads that parse_opt would normally set.
   printf '%s\n' 'guest_pretty="Test"'
   printf '%s\n' 'start_time=0'
   printf '%s\n' 'set -o errexit'
   printf '%s\n' 'set -o nounset'
   printf '%s\n' 'set -o pipefail'
   printf '%s\n' 'set -o errtrace'
   printf '%s\n' 'shopt -s inherit_errexit'
   ## Arm the real ERR/EXIT trap, then raise a genuine error.
   printf '%s\n' 'set_trap'
   printf '%s\n' 'false'
   pad_line='## padding so pr streams well past the pipe buffer before head closes it'
   for _i in $( seq 1 6000 ); do
      printf '%s\n' "${pad_line}"
   done
} > "${driver}"

## Run the driver as a child and capture its exit status. 'timeout' bounds a
## possible runaway re-entrant loop on the old code so the test never hangs.
rc=0
STANDALONE="${standalone}" timeout --kill-after=5 30 bash "${driver}" >/dev/null 2>&1 \
   || rc="$?"

## 'false' makes the genuine exit code 1. The fixed handler must propagate it.
if [ "${rc}" -eq 1 ]; then
   ok "handle_exit propagates the real exit code (1), not a SIGPIPE"
else
   notok "handle_exit did not exit with the real code (rc=${rc})" \
      "141 = the pr|head SIGPIPE re-entry; 124/137 = a runaway re-entrant loop"
fi

printf '%s\n' ""
printf '%s\n' "===== dist-installer-cli handle_exit no-SIGPIPE: ${pass_count} pass, ${fail_count} fail ====="
[ "${fail_count}" -eq 0 ]
