#!/bin/bash

## Copyright (C) 2026 - 2026 ENCRYPTED SUPPORT LLC <adrelanos@whonix.org>
## See the file COPYING for copying conditions.

## AI-Assisted

## DRIFT GUARD: dist-installer-cli-standalone is an autogenerated file -- an inline
## copy of the helper-scripts libraries dist-installer-cli sources, produced by
## build-dist-installer-cli. Nothing regenerates it at build time, so a helper-scripts
## change that is NOT mirrored into the committed standalone drifts silently: the
## fresh cowbuilder chroot (no helper-scripts installed) then runs STALE library code.
## That is exactly how a get_os / is_integer fix can be present in helper-scripts yet
## absent from the standalone the VirtualBox installer actually runs.
##
## This regenerates the standalone from the pinned helper-scripts checkout (the
## generator emits canonical /usr/libexec markers, so the output is byte-reproducible)
## and asserts it is byte-identical to the committed file. A diff means the standalone
## must be regenerated (PROHIBITED_TARGETS_GUARD_ALLOW=1 build-dist-installer-cli) and
## recommitted. No root, no network.
##
## Exit: 0 pass | 1 fail. A missing subject, helper-scripts, shellcheck or git is
## FATAL (exit 1), never a silent skip.

set -o errexit
set -o nounset
set -o pipefail
set -o errtrace
shopt -s inherit_errexit
shopt -s shift_verbose
export LC_ALL=C

repo="${USABILITY_MISC_REPO:-}"
if [ -z "${repo}" ]; then
   repo="${HOME}/derivative-maker/packages/kicksecure/usability-misc"
fi
committed="${repo}/usr/share/usability-misc/dist-installer-cli-standalone"
generator="${repo}/usr/share/usability-misc/build-dist-installer-cli"
template="${repo}/usr/bin/dist-installer-cli"

for subject in "${committed}" "${generator}" "${template}"; do
   if [ ! -r "${subject}" ]; then
      printf '%s\n' "FATAL: not readable: '${subject}'" >&2
      printf '%s\n' "set USABILITY_MISC_REPO to a usability-misc checkout." >&2
      exit 1
   fi
done

## The standalone inlines helper-scripts, so a helper-scripts checkout is the
## SUBJECT here (not auxiliary): its absence is an environment bug, not a skip.
helper_scripts_path="${HELPER_SCRIPTS_PATH:-}"
if [ -z "${helper_scripts_path}" ] \
   && [ -d "${repo}/../helper-scripts/usr/libexec/helper-scripts" ]; then
   helper_scripts_path="${repo}/../helper-scripts"
fi
if [ ! -d "${helper_scripts_path:-}/usr/libexec/helper-scripts" ]; then
   printf '%s\n' "FATAL: no helper-scripts checkout (HELPER_SCRIPTS_PATH unset and no sibling)." >&2
   printf '%s\n' "wire HELPER_SCRIPTS_PATH (dist-ai-tests.helper-scripts: true) at a checkout." >&2
   exit 1
fi

## style-ok: no-has -- checks external build tools, before any helper-scripts source.
for tool in shellcheck git; do
   if ! command -v "${tool}" >/dev/null; then
      printf '%s\n' "FATAL: '${tool}' not on PATH (required to regenerate the standalone)." >&2
      exit 1
   fi
done

work="$(mktemp --directory)"
# shellcheck disable=SC2317  # invoked via the EXIT trap below
cleanup_handler() {
   safe-rm --recursive --force -- "${work}"
}
trap cleanup_handler EXIT

## Reproduce the generator's expected layout (usr/bin + usr/share/usability-misc),
## in a throwaway git repo so its 'git rev-parse --show-toplevel' resolves here and
## the real committed file is never touched.
mkdir --parents -- "${work}/usr/bin" "${work}/usr/share/usability-misc"
cp -- "${template}" "${work}/usr/bin/dist-installer-cli"
cp -- "${generator}" "${work}/usr/share/usability-misc/build-dist-installer-cli"
git -C "${work}" init -q

regenerated="${work}/usr/share/usability-misc/dist-installer-cli-standalone"
gen_log="${work}/gen.log"
if ! HELPER_SCRIPTS_PATH="${helper_scripts_path}" \
      bash "${work}/usr/share/usability-misc/build-dist-installer-cli" \
      >"${gen_log}" 2>&1; then
   printf '%s\n' "FAIL: build-dist-installer-cli errored while regenerating:" >&2
   cat -- "${gen_log}" >&2
   exit 1
fi

if diff -u -- "${committed}" "${regenerated}" >"${work}/drift.diff"; then
   printf '%s\n' "PASS: dist-installer-cli-standalone matches a regenerate from the pinned helper-scripts"
   printf '%s\n' ""
   printf '%s\n' "===== standalone drift guard: 1 pass, 0 fail ====="
   exit 0
fi

printf '%s\n' "FAIL: dist-installer-cli-standalone has DRIFTED from the pinned helper-scripts." >&2
printf '%s\n' "Regenerate + recommit it:" >&2
printf '%s\n' "  PROHIBITED_TARGETS_GUARD_ALLOW=1 build-dist-installer-cli   # inside the usability-misc checkout" >&2
printf '%s\n' "committed (<) vs regenerated (>):" >&2
head --lines=200 -- "${work}/drift.diff" >&2
printf '%s\n' ""
printf '%s\n' "===== standalone drift guard: 0 pass, 1 fail ====="
exit 1
