usr/bin/developer-meta-files-tests usr/bin/
usr/share/developer-meta-files-tests/test_pre_push_static_style_rules.sh usr/share/developer-meta-files-tests/
usr/share/developer-meta-files-tests/test_dm_review_branch.sh usr/share/developer-meta-files-tests/
usr/share/developer-meta-files-tests/test_comments_audit_history.sh usr/share/developer-meta-files-tests/
usr/share/developer-meta-files-tests/test_dm_packages_html_generator.sh usr/share/developer-meta-files-tests/
usr/share/developer-meta-files-tests/dm_review_branch_tty.py usr/share/developer-meta-files-tests/
